# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-22 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cross_name_hash', models.CharField(db_index=True, max_length=32, unique=True)),
                ('cross_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField()),
                ('open_until', models.DateTimeField()),
                ('public', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('min_votes', models.PositiveSmallIntegerField()),
                ('max_votes', models.PositiveSmallIntegerField()),
                ('binary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField()),
                ('open_until', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alumnus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Alumnus')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='PollVoteOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField()),
                ('poll_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PollOption')),
                ('poll_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PollVote')),
            ],
        ),
    ]
